/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;

import botones.TextoPorDefecto;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class frmMenuPrincipal01 extends javax.swing.JFrame {

    /**
     * Creates new form frmWelcome
     */
    public frmMenuPrincipal01() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //this.setExtendedState(6);
        TextoPorDefecto defecto;
        new TextoPorDefecto("   username", txtuserName1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupsalir = new javax.swing.JPopupMenu();
        itenvolver = new javax.swing.JMenuItem();
        itensalir = new javax.swing.JMenuItem();
        popupbuscar = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        popupRegistrar = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        popupListar = new javax.swing.JPopupMenu();
        jLabel4 = new javax.swing.JLabel();
        menuflotantederecho = new javax.swing.JPanel();
        txt_Usuario1 = new javax.swing.JTextField();
        txtuserName1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        menuflotanteRegistrar = new javax.swing.JPanel();
        txt_Usuario3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        menuflotanteBuscar = new javax.swing.JPanel();
        txt_Usuario4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        menuflotanteListar = new javax.swing.JPanel();
        txt_Usuario5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        itenvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/ATRAS.png"))); // NOI18N
        itenvolver.setText("Cerrar Sesión");
        itenvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itenvolverActionPerformed(evt);
            }
        });
        popupsalir.add(itenvolver);

        itensalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/ARELANTE.png"))); // NOI18N
        itensalir.setText("         Salir");
        itensalir.setBorder(null);
        itensalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itensalir.setOpaque(false);
        itensalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itensalirActionPerformed(evt);
            }
        });
        popupsalir.add(itensalir);

        jMenuItem1.setText("jMenuItem1");
        popupbuscar.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        popupbuscar.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        popupbuscar.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        popupRegistrar.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem5");
        popupRegistrar.add(jMenuItem5);

        jMenuItem6.setText("jMenuItem6");
        popupRegistrar.add(jMenuItem6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(2);
        setMinimumSize(new java.awt.Dimension(800, 550));
        setName("framdeInicio"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel4.setText("Usuario:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 290, 47, 20);

        menuflotantederecho.setComponentPopupMenu(popupsalir);
        menuflotantederecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuflotantederecho.setOpaque(false);
        menuflotantederecho.setLayout(null);

        txt_Usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Usuario1ActionPerformed(evt);
            }
        });
        menuflotantederecho.add(txt_Usuario1);
        txt_Usuario1.setBounds(280, 320, 255, 24);

        txtuserName1.setBorder(null);
        txtuserName1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtuserName1.setSelectionColor(new java.awt.Color(255, 255, 255));
        menuflotantederecho.add(txtuserName1);
        txtuserName1.setBounds(10, 10, 110, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/ID USUARIO.png"))); // NOI18N
        jLabel7.setText("_");
        menuflotantederecho.add(jLabel7);
        jLabel7.setBounds(120, 0, 40, 50);

        getContentPane().add(menuflotantederecho);
        menuflotantederecho.setBounds(630, 0, 170, 60);

        menuflotanteRegistrar.setComponentPopupMenu(popupbuscar);
        menuflotanteRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuflotanteRegistrar.setOpaque(false);
        menuflotanteRegistrar.setLayout(null);

        txt_Usuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Usuario3ActionPerformed(evt);
            }
        });
        menuflotanteRegistrar.add(txt_Usuario3);
        txt_Usuario3.setBounds(280, 320, 255, 24);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/LAPIZ.png"))); // NOI18N
        jLabel8.setText("Registrar");
        menuflotanteRegistrar.add(jLabel8);
        jLabel8.setBounds(10, 20, 110, 30);

        getContentPane().add(menuflotanteRegistrar);
        menuflotanteRegistrar.setBounds(310, 0, 130, 60);

        menuflotanteBuscar.setComponentPopupMenu(popupbuscar);
        menuflotanteBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuflotanteBuscar.setOpaque(false);
        menuflotanteBuscar.setLayout(null);

        txt_Usuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Usuario4ActionPerformed(evt);
            }
        });
        menuflotanteBuscar.add(txt_Usuario4);
        txt_Usuario4.setBounds(280, 320, 255, 24);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/LUPA.png"))); // NOI18N
        jLabel10.setText("Buscar");
        menuflotanteBuscar.add(jLabel10);
        jLabel10.setBounds(20, 10, 110, 50);

        getContentPane().add(menuflotanteBuscar);
        menuflotanteBuscar.setBounds(450, 0, 130, 60);

        menuflotanteListar.setComponentPopupMenu(popupbuscar);
        menuflotanteListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuflotanteListar.setOpaque(false);
        menuflotanteListar.setLayout(null);

        txt_Usuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Usuario5ActionPerformed(evt);
            }
        });
        menuflotanteListar.add(txt_Usuario5);
        txt_Usuario5.setBounds(280, 320, 255, 24);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/CARPETA CON PAPEL.png"))); // NOI18N
        jLabel9.setText("Listar");
        menuflotanteListar.add(jLabel9);
        jLabel9.setBounds(10, 20, 110, 30);

        getContentPane().add(menuflotanteListar);
        menuflotanteListar.setBounds(170, 0, 130, 60);

        fondo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/menu3.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 800, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itenvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itenvolverActionPerformed
        //regresar a welcome
        int dialog = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿Desea cerrar seción?", "Volver", dialog);
        if (resultado == 0) {
            frmWelcome_00 Traer = new frmWelcome_00();
            Traer.setVisible(true);
        }
    }//GEN-LAST:event_itenvolverActionPerformed

    private void itensalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itensalirActionPerformed
        //Cerrar
        int dialog = JOptionPane.YES_NO_OPTION;
        int resultado= JOptionPane.showConfirmDialog(this, "¿Desea Salir?","Salir",dialog);
        if (resultado==0)
        System.exit(0);
    }//GEN-LAST:event_itensalirActionPerformed

    private void txt_Usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Usuario1ActionPerformed

    private void txt_Usuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Usuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Usuario3ActionPerformed

    private void txt_Usuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Usuario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Usuario4ActionPerformed

    private void txt_Usuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Usuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Usuario5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JMenuItem itensalir;
    private javax.swing.JMenuItem itenvolver;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel menuflotanteBuscar;
    private javax.swing.JPanel menuflotanteListar;
    private javax.swing.JPanel menuflotanteRegistrar;
    private javax.swing.JPanel menuflotantederecho;
    private javax.swing.JPopupMenu popupListar;
    private javax.swing.JPopupMenu popupRegistrar;
    private javax.swing.JPopupMenu popupbuscar;
    private javax.swing.JPopupMenu popupsalir;
    private javax.swing.JTextField txt_Usuario1;
    private javax.swing.JTextField txt_Usuario3;
    private javax.swing.JTextField txt_Usuario4;
    private javax.swing.JTextField txt_Usuario5;
    private javax.swing.JTextField txtuserName1;
    // End of variables declaration//GEN-END:variables
}
