/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;

import botones.TextoPorDefecto;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class frmMenuPrincipal011 extends javax.swing.JFrame {

    /**
     * Creates new form frmWelcome
     */
    frmWelcome_00 mensajeF = new frmWelcome_00();
    public frmMenuPrincipal011() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //this.setExtendedState(6);
        TextoPorDefecto defecto;
        new TextoPorDefecto("   username", txtuserName);
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupsalir = new javax.swing.JPopupMenu();
        itenvolver = new javax.swing.JMenuItem();
        itensalir = new javax.swing.JMenuItem();
        popupMisOp = new javax.swing.JPopupMenu();
        itenTranferencia = new javax.swing.JMenuItem();
        itenPagos = new javax.swing.JMenuItem();
        itenRetiro = new javax.swing.JMenuItem();
        popupMisCuentas = new javax.swing.JPopupMenu();
        ItenCuentaSoles = new javax.swing.JMenuItem();
        itenCuentaDolares = new javax.swing.JMenuItem();
        itenAllCuentas = new javax.swing.JMenuItem();
        menuflotantederecho = new javax.swing.JPanel();
        txtuserName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        menuflotanteMisOp = new javax.swing.JPanel();
        lblMisOperacionesIcono = new javax.swing.JLabel();
        panelInicio = new javax.swing.JPanel();
        lblInicioIcono = new javax.swing.JLabel();
        panelCuentas = new javax.swing.JPanel();
        lblMiCuentasIcono1 = new javax.swing.JLabel();
        lblmensaje = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        itenvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/ATRAS.png"))); // NOI18N
        itenvolver.setText("Cerrar Sesión");
        itenvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itenvolverActionPerformed(evt);
            }
        });
        popupsalir.add(itenvolver);

        itensalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/ARELANTE.png"))); // NOI18N
        itensalir.setText("         Salir");
        itensalir.setBorder(null);
        itensalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itensalir.setOpaque(false);
        itensalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itensalirActionPerformed(evt);
            }
        });
        popupsalir.add(itensalir);

        itenTranferencia.setText("Transferencias");
        popupMisOp.add(itenTranferencia);

        itenPagos.setText("Pagos ");
        itenPagos.setOpaque(false);
        popupMisOp.add(itenPagos);

        itenRetiro.setText("Retiro");
        popupMisOp.add(itenRetiro);

        popupMisCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ItenCuentaSoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/cerdoSoles.png"))); // NOI18N
        ItenCuentaSoles.setText("Cuentas en Soles");
        ItenCuentaSoles.setBorder(null);
        ItenCuentaSoles.setBorderPainted(false);
        ItenCuentaSoles.setContentAreaFilled(false);
        ItenCuentaSoles.setOpaque(false);
        ItenCuentaSoles.setVerifyInputWhenFocusTarget(false);
        popupMisCuentas.add(ItenCuentaSoles);

        itenCuentaDolares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/cerdoDolar.png"))); // NOI18N
        itenCuentaDolares.setText("Cuentas en Dolares");
        itenCuentaDolares.setBorder(null);
        itenCuentaDolares.setBorderPainted(false);
        itenCuentaDolares.setContentAreaFilled(false);
        itenCuentaDolares.setOpaque(false);
        popupMisCuentas.add(itenCuentaDolares);

        itenAllCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/cerdoSolo.png"))); // NOI18N
        itenAllCuentas.setText("Todas las cuentas");
        itenAllCuentas.setBorder(null);
        itenAllCuentas.setBorderPainted(false);
        itenAllCuentas.setContentAreaFilled(false);
        itenAllCuentas.setOpaque(false);
        popupMisCuentas.add(itenAllCuentas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(2);
        setMinimumSize(new java.awt.Dimension(800, 550));
        setName("framdeInicio"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(null);

        menuflotantederecho.setComponentPopupMenu(popupsalir);
        menuflotantederecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuflotantederecho.setOpaque(false);
        menuflotantederecho.setLayout(null);

        txtuserName.setBorder(null);
        txtuserName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtuserName.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtuserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserNameActionPerformed(evt);
            }
        });
        menuflotantederecho.add(txtuserName);
        txtuserName.setBounds(10, 10, 110, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/ID USUARIO.png"))); // NOI18N
        jLabel7.setText("_");
        menuflotantederecho.add(jLabel7);
        jLabel7.setBounds(120, 0, 40, 50);

        getContentPane().add(menuflotantederecho);
        menuflotantederecho.setBounds(630, 0, 170, 60);

        menuflotanteMisOp.setComponentPopupMenu(popupMisOp);
        menuflotanteMisOp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuflotanteMisOp.setOpaque(false);
        menuflotanteMisOp.setLayout(null);

        lblMisOperacionesIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/4544829 - business comerce delivery mastercard shop(1).png"))); // NOI18N
        lblMisOperacionesIcono.setText("Mis Operaciones");
        menuflotanteMisOp.add(lblMisOperacionesIcono);
        lblMisOperacionesIcono.setBounds(10, 20, 150, 30);

        getContentPane().add(menuflotanteMisOp);
        menuflotanteMisOp.setBounds(450, 0, 160, 60);

        panelInicio.setToolTipText("");
        panelInicio.setOpaque(false);
        panelInicio.setLayout(null);

        lblInicioIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/CASITA.png"))); // NOI18N
        lblInicioIcono.setText("Inicio");
        panelInicio.add(lblInicioIcono);
        lblInicioIcono.setBounds(0, 20, 70, 30);

        getContentPane().add(panelInicio);
        panelInicio.setBounds(230, 0, 70, 60);

        panelCuentas.setToolTipText("");
        panelCuentas.setComponentPopupMenu(popupMisCuentas);
        panelCuentas.setOpaque(false);
        panelCuentas.setLayout(null);

        lblMiCuentasIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS NEGRITAS/cerdoSolo.png"))); // NOI18N
        lblMiCuentasIcono1.setText("Mis Cuentas");
        panelCuentas.add(lblMiCuentasIcono1);
        lblMiCuentasIcono1.setBounds(0, 20, 106, 32);

        getContentPane().add(panelCuentas);
        panelCuentas.setBounds(330, 0, 110, 60);

        lblmensaje.setText("_");
        getContentPane().add(lblmensaje);
        lblmensaje.setBounds(570, 110, 7, 16);

        fondo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/menu3.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 800, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itenvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itenvolverActionPerformed
        //regresar a welcome
        int dialog = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿Desea cerrar seción?", "Volver", dialog);
        if (resultado == 0) {
            frmWelcome_00 Traer = new frmWelcome_00();
            Traer.setVisible(true);
        }
    }//GEN-LAST:event_itenvolverActionPerformed

    private void itensalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itensalirActionPerformed
        //Cerrar
        int dialog = JOptionPane.YES_NO_OPTION;
        int resultado= JOptionPane.showConfirmDialog(this, "¿Desea Salir?","Salir",dialog);
        if (resultado==0)
        System.exit(0);
    }//GEN-LAST:event_itensalirActionPerformed

    private void txtuserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserNameActionPerformed
        // cccc

    }//GEN-LAST:event_txtuserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal011.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal011.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal011.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal011.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal011().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItenCuentaSoles;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenuItem itenAllCuentas;
    private javax.swing.JMenuItem itenCuentaDolares;
    private javax.swing.JMenuItem itenPagos;
    private javax.swing.JMenuItem itenRetiro;
    private javax.swing.JMenuItem itenTranferencia;
    private javax.swing.JMenuItem itensalir;
    private javax.swing.JMenuItem itenvolver;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblInicioIcono;
    private javax.swing.JLabel lblMiCuentasIcono1;
    private javax.swing.JLabel lblMisOperacionesIcono;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JPanel menuflotanteMisOp;
    private javax.swing.JPanel menuflotantederecho;
    private javax.swing.JPanel panelCuentas;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPopupMenu popupMisCuentas;
    private javax.swing.JPopupMenu popupMisOp;
    private javax.swing.JPopupMenu popupsalir;
    private javax.swing.JTextField txtuserName;
    // End of variables declaration//GEN-END:variables
}
