/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;

import botones.TextoPorDefecto;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class frmregistrodelCliente01 extends javax.swing.JFrame {

    /**
     * Creates new form frmWelcome
     */
    public frmregistrodelCliente01() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        TextoPorDefecto defecto;
        new TextoPorDefecto("   Nombre de usuario", txt_UsuarioNuevoRegistro);
        new TextoPorDefecto("   Alexander", txt_NomreUNuevoRegistro);
        new TextoPorDefecto("   Briones", txt_ApellidoUNuevoRegistro);
        new TextoPorDefecto("   alexanderbvart@gmail.com", txt_CorreoUNuevoRegistro);
        new TextoPorDefecto("   999666969", txt_TelefonoUNuevoRegistro);
        new TextoPorDefecto("   Pacasmayo", txt_CiudadUNuevoRegistro);
        new TextoPorDefecto("   Contraseña", txt_ContraseñaNurvoReg);
        new TextoPorDefecto("   Verifique su contraseña", txt_ContraseñaNConfReg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();
        lbl_usuarioUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ContraseñaNurvoReg = new javax.swing.JTextField();
        txt_UsuarioNuevoRegistro = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_ContraseñaNConfReg = new javax.swing.JTextField();
        lbl_nombre_usuario = new javax.swing.JLabel();
        txt_NomreUNuevoRegistro = new javax.swing.JTextField();
        lb_lApelldos_usuarios = new javax.swing.JLabel();
        txt_ApellidoUNuevoRegistro = new javax.swing.JTextField();
        lbl_usuarioUser1 = new javax.swing.JLabel();
        txt_CorreoUNuevoRegistro = new javax.swing.JTextField();
        lbl_nombre_usuario1 = new javax.swing.JLabel();
        txt_TelefonoUNuevoRegistro = new javax.swing.JTextField();
        lbl__DireccionUusuarios = new javax.swing.JLabel();
        txt_CiudadUNuevoRegistro = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jfndo = new javax.swing.JLabel();

        fondo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/welcomeSesion.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(2);
        setMinimumSize(new java.awt.Dimension(800, 550));
        setName("framdeInicio"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(null);

        lbl_usuarioUser.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lbl_usuarioUser.setText("Usuario:");
        getContentPane().add(lbl_usuarioUser);
        lbl_usuarioUser.setBounds(270, 120, 47, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 320, 69, 20);

        txt_ContraseñaNurvoReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ContraseñaNurvoReg.setBorder(null);
        txt_ContraseñaNurvoReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_ContraseñaNurvoReg.setOpaque(false);
        txt_ContraseñaNurvoReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ContraseñaNurvoRegActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ContraseñaNurvoReg);
        txt_ContraseñaNurvoReg.setBounds(270, 340, 250, 30);

        txt_UsuarioNuevoRegistro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_UsuarioNuevoRegistro.setBorder(null);
        txt_UsuarioNuevoRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_UsuarioNuevoRegistro.setOpaque(false);
        txt_UsuarioNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsuarioNuevoRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_UsuarioNuevoRegistro);
        txt_UsuarioNuevoRegistro.setBounds(270, 140, 250, 30);

        btnActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton-registrarce.png"))); // NOI18N
        btnActualizar.setMnemonic('A');
        btnActualizar.setBorder(null);
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setIconTextGap(-26);
        btnActualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton-registrarce.png"))); // NOI18N
        btnActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/boton-registrarce.png"))); // NOI18N
        btnActualizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(270, 430, 255, 28);

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel4.setText("Confirmar contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 370, 128, 20);

        txt_ContraseñaNConfReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ContraseñaNConfReg.setBorder(null);
        txt_ContraseñaNConfReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_ContraseñaNConfReg.setOpaque(false);
        txt_ContraseñaNConfReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ContraseñaNConfRegActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ContraseñaNConfReg);
        txt_ContraseñaNConfReg.setBounds(270, 390, 250, 30);

        lbl_nombre_usuario.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lbl_nombre_usuario.setText("Nombre:");
        getContentPane().add(lbl_nombre_usuario);
        lbl_nombre_usuario.setBounds(270, 170, 70, 20);

        txt_NomreUNuevoRegistro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NomreUNuevoRegistro.setBorder(null);
        txt_NomreUNuevoRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_NomreUNuevoRegistro.setOpaque(false);
        txt_NomreUNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomreUNuevoRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_NomreUNuevoRegistro);
        txt_NomreUNuevoRegistro.setBounds(270, 190, 120, 30);

        lb_lApelldos_usuarios.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lb_lApelldos_usuarios.setText("Apellidos:");
        getContentPane().add(lb_lApelldos_usuarios);
        lb_lApelldos_usuarios.setBounds(400, 170, 70, 20);

        txt_ApellidoUNuevoRegistro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ApellidoUNuevoRegistro.setBorder(null);
        txt_ApellidoUNuevoRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_ApellidoUNuevoRegistro.setOpaque(false);
        txt_ApellidoUNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoUNuevoRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ApellidoUNuevoRegistro);
        txt_ApellidoUNuevoRegistro.setBounds(400, 190, 120, 30);

        lbl_usuarioUser1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lbl_usuarioUser1.setText("Correo:");
        getContentPane().add(lbl_usuarioUser1);
        lbl_usuarioUser1.setBounds(270, 220, 43, 20);

        txt_CorreoUNuevoRegistro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_CorreoUNuevoRegistro.setBorder(null);
        txt_CorreoUNuevoRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_CorreoUNuevoRegistro.setOpaque(false);
        txt_CorreoUNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CorreoUNuevoRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_CorreoUNuevoRegistro);
        txt_CorreoUNuevoRegistro.setBounds(270, 240, 250, 30);

        lbl_nombre_usuario1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lbl_nombre_usuario1.setText("Telefono:");
        getContentPane().add(lbl_nombre_usuario1);
        lbl_nombre_usuario1.setBounds(270, 270, 70, 20);

        txt_TelefonoUNuevoRegistro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_TelefonoUNuevoRegistro.setBorder(null);
        txt_TelefonoUNuevoRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_TelefonoUNuevoRegistro.setOpaque(false);
        txt_TelefonoUNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TelefonoUNuevoRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_TelefonoUNuevoRegistro);
        txt_TelefonoUNuevoRegistro.setBounds(270, 290, 120, 30);

        lbl__DireccionUusuarios.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        lbl__DireccionUusuarios.setText("Direccion:");
        getContentPane().add(lbl__DireccionUusuarios);
        lbl__DireccionUusuarios.setBounds(400, 270, 70, 20);

        txt_CiudadUNuevoRegistro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_CiudadUNuevoRegistro.setBorder(null);
        txt_CiudadUNuevoRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_CiudadUNuevoRegistro.setOpaque(false);
        txt_CiudadUNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CiudadUNuevoRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_CiudadUNuevoRegistro);
        txt_CiudadUNuevoRegistro.setBounds(400, 290, 120, 30);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Util/LINEAS LITE/EQUIS CIRCULO.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(490, 80, 32, 32);

        jfndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/welcomeSesion.png"))); // NOI18N
        jfndo.setText("r");
        getContentPane().add(jfndo);
        jfndo.setBounds(0, 0, 800, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ContraseñaNurvoRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ContraseñaNurvoRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContraseñaNurvoRegActionPerformed

    private void txt_UsuarioNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsuarioNuevoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsuarioNuevoRegistroActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txt_ContraseñaNConfRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ContraseñaNConfRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContraseñaNConfRegActionPerformed

    private void txt_NomreUNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomreUNuevoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomreUNuevoRegistroActionPerformed

    private void txt_ApellidoUNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoUNuevoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoUNuevoRegistroActionPerformed

    private void txt_CorreoUNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CorreoUNuevoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoUNuevoRegistroActionPerformed

    private void txt_TelefonoUNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TelefonoUNuevoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TelefonoUNuevoRegistroActionPerformed

    private void txt_CiudadUNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CiudadUNuevoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CiudadUNuevoRegistroActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Cerrar
        int dialog = JOptionPane.YES_NO_OPTION;
        int resultado= JOptionPane.showConfirmDialog(this, "¿Desea salir?","Salir",dialog);
        if (resultado==0)
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmregistrodelCliente01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmregistrodelCliente01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmregistrodelCliente01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmregistrodelCliente01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmregistrodelCliente01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jfndo;
    private javax.swing.JLabel lb_lApelldos_usuarios;
    private javax.swing.JLabel lbl__DireccionUusuarios;
    private javax.swing.JLabel lbl_nombre_usuario;
    private javax.swing.JLabel lbl_nombre_usuario1;
    private javax.swing.JLabel lbl_usuarioUser;
    private javax.swing.JLabel lbl_usuarioUser1;
    private javax.swing.JTextField txt_ApellidoUNuevoRegistro;
    private javax.swing.JTextField txt_CiudadUNuevoRegistro;
    private javax.swing.JTextField txt_ContraseñaNConfReg;
    private javax.swing.JTextField txt_ContraseñaNurvoReg;
    private javax.swing.JTextField txt_CorreoUNuevoRegistro;
    private javax.swing.JTextField txt_NomreUNuevoRegistro;
    private javax.swing.JTextField txt_TelefonoUNuevoRegistro;
    private javax.swing.JTextField txt_UsuarioNuevoRegistro;
    // End of variables declaration//GEN-END:variables
}
